name = "vite-react-18-ssr-streaming"
compatibility_date = "2021-09-29"
account_id = ""
workers_dev = true
type = "javascript"
compatibility_flags = ["streams_enable_constructors"]

[build]
command = "pnpm run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./dist/client"
entry-point = "."
